exclude: ^(build|third-party)/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-json
  - id: check-yaml
    args: ["--allow-multiple-documents", "--unsafe"]
  - id: mixed-line-ending
    args: ["--fix=lf"]
  - id: pretty-format-json
    args:  ["--autofix", "--indent=2", "--no-sort-keys"]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.5
  hooks:
  - id: clang-format
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.9.3
  hooks:
  - id: gersemi
    args: ["-i"]
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
  - id: shellcheck
  - id: shfmt
    args: ["-w"]
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
    args: ["-i"]
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: local
  hooks:
  - id: license-header-check
    name: check the license header of all files
    entry: bash -c 'python scripts/license-update.py'
    language: system
    pass_filenames: false